### ISSUE TITLE
Select row programatically - v 0.9.0

### ISSUE THREAD

**Issue by cleever** [daniel-nagy/md-data-table#216]
How can I select a row programmatically in new v 0.9.0 ?
I did not see how to access Key object in directive or a select method.
In the previous version, I used to change the selected items array and it used to work.

**Comment by daniel-nagy** [comment]
It is possible but a little cumbersome. Currently you would have to find the table element and get the controller and then manually add the key.

```javascript
var tableCrl = $element.find('table').controller('mdTable');

// assuming you are using an id prop on the item as a key
self.selected.push(item);
tableCrl.keys[item.id] = item;
```

I think instead I will add a companion `md.table.select` event that will allow you to select an item.

```javascript
$scope.$broadcast(`md.table.select`, item, key);
```

**Comment by cleever** [comment]
I think that create a new function that supports (item, key) parameters is a better idea.

Another option is to expose "keys" array like "selected" array model.

```html
<table md-table md-row-select ng-model="selected" md-keys-model="keys">
```

```javascript
$scope.selected.push(item);
$scope.keys[item.id] = item;
```

or something like that.

**Comment by daniel-nagy** [comment]
I'm trying to think of the best way to do this. I'm not really a fan of the scope events because if you have multiple tables in the same scope it is impossible to communicate directly with one table.

Another thing I was thinking is, if someone is using a key for one item in the table they are most likely using keys for all items in the table so maybe I can force the developer to use an object for selected items instead of an array.

/// if not using keys
$scope.select = [itemOne, itemTwo];

// if using keys
$scope.selected = {
  keyOne: itemOne,
  keyTwo: itemTwo
};

This would allow the developer to freely add and remove items within their controller and it would be more efficient.

**Comment by cleever** [comment]
Sure. The question is the better way to do that.

But I liked your new suggestion. It could work really well.

**Comment by cleever** [comment]
Version 0.9.1 fixes de issue.

Thanks for the quick assistance.
