### ISSUE TITLE
hide columns

### ISSUE THREAD

**Issue by scriptsure** [daniel-nagy/md-data-table#253]
i know that there are some other cases that are having issues with hiding columns. But the following does not work as well when using material design 1.0.1:

"td hide-lt-md  md-cell>{{message.sender}}</td"

So all the media type hid and show also are not working. BUT ng-show does work....

**Comment by Koslun** [comment]
After upgrading to 0.9.x I actually noticed a regression concerning hiding columns with ng-show. Hiding the first column results with a new first column that has no padding to the left. 

Can see this in the following code pen: http://codepen.io/Koslun/pen/KVZKWa?editors=101, where I added two check boxes for hiding and showing the "calories" and "dessert" columns respectively. Hiding the "calories" column works fine while hiding the "dessert" column however leaves you with the "type" column that shows no padding to the left of table. Either touching the selection boxes or the containing card.

**Comment by scriptsure** [comment]
actually after further research it seems that i cant get hide-lt-md to work at all.... think this is an angular issue. 

I do know what you are saying about the padding though on the first column... if hidden the second column gets pushed up against, in my case the checkbox.

**Comment by daniel-nagy** [comment]
@scriptsure see my response to @Koslun [here](https://github.com/daniel-nagy/md-data-table/issues/258).

Yes I believe some of the media query directives in Angular Material do not behaving as expect. In the example [Codepen](http://codepen.io/anon/pen/YwGJVr?editors=101) you'll notice that I am using some on the last few columns and they work.

`ng-show` and Angular Material media directives are only going to be an issue if you hide the first or last cell because these cells have different padding then the rest. You can always manually fix the padding when you hide the first or last cell.
