### ISSUE TITLE
No padding when hiding first column with ng-show

### ISSUE THREAD

**Issue by Koslun** [daniel-nagy/md-data-table#258]
After upgrading to 0.9.x I noticed a regression concerning hiding columns with ng-show. When hiding the first column the new column that becomes first does not have any padding to the left. Hiding the other columns however still works as expected.

The issue is shown in the following code pen: http://codepen.io/Koslun/pen/KVZKWa?editors=101, where I added two check boxes for hiding and showing the "calories" and "dessert" columns respectively. Hiding the "calories" column works fine while hiding the "dessert" column (the first column) however leaves you with the "type" column that shows no padding to the left of the table. Resulting in the column either touching the selection boxes or the containing card.

**Comment by daniel-nagy** [comment]
> After upgrading to 0.9.x I noticed a regression concerning hiding columns with ng-show. When hiding the first column the new column that becomes first does not have any padding to the left. Hiding the other columns however still works as expected.

This is because cell padding is determined by the index of the cell using `nth-child` CSS selectors. `ngShow` does not remove the element from the DOM, it just hides it. If you use `ng-if` it will behave as expected. I've modified your [Codepen](http://codepen.io/anon/pen/zrprBb?editors=101) to use `ng-if`.

There may be reasons why you would want to use `ng-show` instead of `ng-if`, in that case this is still an issue. I'd probably need to break the rules for [column padding](https://www.google.com/design/spec/components/data-tables.html#data-tables-specs) like I did in earlier versions where the padding was evenly distributed between cells.

**Comment by Koslun** [comment]
@daniel-nagy thanks, that explains the source of the problem very neatly.

I don't see any reason to use `ng-show` over `ng-if` in my application so just changed to using `ng-if` as you suggested

More generally, like you said, there may be reasons for using `ng-show` and in that case this would still be an issue. I however don't think it's a very common use-case and if you figure the easiest fix is breaking column padding rules I think it might be just even easier to just leave it up to the developer to throw in some `ng-style` or `ng-class` to correct it themselves in the off chance that they both need to use `ng-show` and use it on the first or last column.

So closing the issue for now.
