### ISSUE TITLE
Horizontal scroll bar in Chrome

### ISSUE THREAD

**Issue by csotomon** [daniel-nagy/md-data-table#279]
Hi, I have a 

table with a lot of columns.

In Internet explorer the module render the scroll bar perfectly, but in chrome dont's works, and my side bar disappears. How can I solve this?

Internet Explorer
![ie](https://cloud.githubusercontent.com/assets/9087039/12853453/1e26bb4a-cc02-11e5-8ae6-3efbc970b626.png)

Chorme
![chrome](https://cloud.githubusercontent.com/assets/9087039/12853457/2347abd4-cc02-11e5-84b3-f177a4167209.png)

**Comment by dbo35** [comment]
easy fix is adding style="overflow-y : scroll"

**Comment by csotomon** [comment]
I inserted the style in the next tags and doesn't works.

md-card
md-table-container
table

**Comment by dbo35** [comment]
I'll check my code and give more detail

**Comment by csotomon** [comment]
Hi, do you have some news about this problem?

**Comment by dbo35** [comment]
trying to find the source of this issue...

in the meantime give different breakpoints fixed widths on the <md-table-container> and set overflow-x:scroll.

something in the table header is causing the entire container to expand indefinitely to fit all columns and is pushing the sidenav / everything else off of the screen instead of keeping to its flexbox.

**Comment by leocaseiro** [comment]
It's working fine for me on Chrome OSX. Make sure you add `<md-content flex layout="column">`. Perhaps you'll need to add a `layout-fill` in it's wrapper:

```html
<main layout-fill>
	<md-content layout="column" flex>
	    <md-table-container>
	        <table md-table>
	            ...
	        </table>
	    </md-table-container>
	</md-content>
</main>
```
