### ISSUE TITLE
Custom Edit Dialog does not work when using resolve

### ISSUE THREAD

**Issue by erikwiklander** [daniel-nagy/md-data-table#294]
When I try to create my custom edit dialog, this fails when using a 'resolve' that makes an ajax request.

The error reads 'Cannot read property getTable of undefined'

Here is link to a Codpen: http://codepen.io/anon/pen/BjEZgg?editors=0010
Please look at row 135 in JS

The problem seems to happen because after the ajax request, currentTarget is no longer available in targetEvent.

I have solved this in my local project by adding target explicitly to the dialog options 
{ target: targetEvent.currentTarget } and modified your code as such:

positionDialog(element, options.targetEvent.currentTarget || options.target);

(There might be a better solution available?)

In any case I would like to thank you for the great work you have done with this.

**Comment by daniel-nagy** [comment]
You are exactly right. There are two ways I can solve this.

1. Create a copy of the `currentTarget` property before the ajax request is made or,
2. Just have the developer pass the table cell element instead of the event object.

For the first one the syntax will be the exact same. For the second one I would get rid of the `targetEvent` property and add a tableCell property,

```javascript
$scope.editComment = function (event, dessert) {
  event.stopPropagation();

  $mdEditDialog.show({
    tableCell: event.currentTarget,
    template: '<md-edit-dialog><form>some autocomplete code left out</form></md-edit-dialog>',
    resolve: { 
      values: $http.get('https://restcountries.eu/rest/v1/alpha/se')
    }
});
```

Do you have a preference either way?

**Comment by erikwiklander** [comment]
Cool,

I don't have any preference really, but my initial feeling is option 1 because:

1. Existing syntax works
2. Works in a similar manner as $mdDialog (which also accepts targetEvent)

But either way is perfectly fine with me.

Thanks!

**Comment by daniel-nagy** [comment]
Fixed!
