### ISSUE TITLE
md-on-deselect and md-on-select called multiple times

### ISSUE THREAD

**Issue by apat183** [daniel-nagy/md-data-table#309]
When clicking the select all checkbox, the md-on-select function is called for every row in the table. Should the behaviour be just once? The reason being for my example, I trigger and graph update based on selected items. So each time a user selects an item it updates the graph, but when you select all it gets triggered multiple times, there are some promises that a used to get relevant data for the graphs and it causes double counting on some items. 

I noticed that a simple  $watchCollection could be used and that only gets triggered once for when an item is selected and deselected or when you select all or deselect. 
```
$scope.$watchCollection('selectedItems', function (newNames, oldNames) {
      console.log('items selected');
    });
```

**Comment by daniel-nagy** [comment]
When you select all items, every item that is not already selected or disabled will be selected. Therefore `md-on-select` will be called for every item that is not already selected or is disabled. I think this is the expected behavior for most people. If you are "doubt counting" items, that seems like a fault in your logic because `md-on-select` should never be called for an item that is already selected.

If you just want to know when there is a change in selected items then `$watchCollection` could work.

**Comment by apat183** [comment]
Thanks, yeah I think for my situation `$watchCollection` works better. Just wanted to confirm this was the expected behaviour. 

You are right it will most likely be something in my logic. It's calling multiple promises based on selected items each time items are selected, I need to update my logic to cancel in current promises each time it's called.
