### ISSUE TITLE
Pagination page selector

### ISSUE THREAD

**Issue by daniel-nagy** [daniel-nagy/md-data-table#38]
It would be nice select a page or at least jump to the first or last page.

**Comment by gligoran** [comment]
This would be cool. Maybe something like Angular UI Bootstrap has: http://angular-ui.github.io/bootstrap/#/pagination Note how it works when you limit the maximum visible buttons.

**Comment by daniel-nagy** [comment]
I'm against the way bootstrap does pagination by displaying the page numbers, this does not work well on mobile. Instead I was planing on adding another drop down menu to select the page like how the 'rows per page' is selected.

This of course will be opted into via an additional attribute. I plan on removing the first and last page links by default and making them opted into as well.

**Comment by gligoran** [comment]
OK, I understand about the bootstrap thing.

I do have another idea, though. What about replacing the '10-15 of 24' with 'Page 3 of 5' and then making the 3 a select like it is for per-row. Essentially I'm talking about how pagination works [here](http://linustechtips.com/main/topic/183-show-off-your-setup/page-249?), but without the bootstrap-like thingy and the click on page counter is an md-select instead of a enter a page number. So '<<  < page 249 of 660 > >>'.

**Comment by daniel-nagy** [comment]
They might not know the page is selectable though unless we show a drop down arrow next to the current page number.

**Comment by leocaseiro** [comment]
is this not the `md-page-select`? If it is, you can close this issue.

**Comment by daniel-nagy** [comment]
@leocaseiro yes, thanks.
