### ISSUE TITLE
sort icon location depending on numeric / non-numeric data looks inconsistent

### ISSUE THREAD

**Issue by jacobuk** [daniel-nagy/md-data-table#399]
![sorticon](https://cloud.githubusercontent.com/assets/8680522/15273961/767c7534-1ac5-11e6-816e-f25a2bc225d1.png)

We have the following code for attaching the sort icon before or after the column header
      if(element.hasClass('md-numeric')) {
        element.prepend(sortIcon);
      } else {
        element.append(sortIcon);
      }

I don't see this mentioned in the standard. To me, it results in an inconsistent look.

**Comment by daniel-nagy** [comment]
If you look at Material Design's documentation for [data tables](https://www.google.com/design/spec/components/data-tables.html#data-tables-interaction) you will see when the columns are right aligned the sort icons are to the left of the column label. I would guess they did this because the icons are hidden until hovered. If they put the sort icons to the right of columns that are right aligned, the column headers would not be aligned with text in the table body.
