### ISSUE TITLE
table flash when using ng-repeat-start

### ISSUE THREAD

**Issue by dandanknight** [daniel-nagy/md-data-table#420]
Hi, hope you can help me with this. Unsure if it's a bug or not.

I'm looking to add "child (or details) rows" using an ng-repeat-start/end. I have my table automatically refresh every 30 or so seconds. My table (cut down) looks like this....

````
<tbody md-body>
    <tr md-row md-select="title" md-select-id="id" md-auto-select ng-repeat-start="title in vm.titles.items">
        <td md-cell>{{title.titleId}}</td>
        <td md-cell>{{title.version}}</td>
        <td md-cell>{{title.titleBrief}}</td>
    </tr>
    <tr ng-repeat-end md-row>
        <td colspan="8" md-cell>I am a child row!!!!!!!!!</td>
    </tr>
</tbody>
````
My issue is that when I use `ng-repeat-start` and `ng-repeat-end` and the table refreshes, there are duplicated items there for a split second. My JS to refresh the code is pretty standard....

````
        function loadTitles() {
            vm.loadTitlesPromise = TitleApiFactory.getTitles(vm.query)
                .then(function (res) {
                    console.log("loaded %s titles", res.data.items.length);
                    vm.titles = res.data;
                    return res.data;
                });
            return vm.loadTitlesPromise;
        }
````

If I use a standard ng-repeat I do not get this. But I can't think of another method of implementing child/detail rows.

I have screen recorded the flash, and uploaded it to YouTube. You can see the duplicated items flash in the table about 2 seconds in. [VIDEO HERE](https://www.youtube.com/watch?v=Z41JEJO1mjc)

Congratulations on a great library by the way, without this I would not have been able to even start my project!

**Comment by dandanknight** [comment]
Isn't this typical. I've been scratching my head for days over this, and 10 mins after I post an issue, I find the solution. For anyone that is interested, add a `track by` to your `ng-repeat-start`, so...

`ng-repeat-start="title in vm.titles.items"`
becomes
`ng-repeat-start="title in vm.titles.items track by $index"`

This seems to prevent the flashing.

**Comment by Mansyn** [comment]
Thanks for the tip. I was having a similar issue with the pagination function getting called twice, I think once for the `ng-repeat-start` and once for the `ng-repeat-end`. But tacking the track by on worked for me.

**Comment by MarkPaulsen** [comment]
Thank you very much for this fix.  Adding the "track by" was half of the solution for me.
The other half was to NOT set the clear the collection (items = [];) before reloading data.

A small suggestion: using a unique property value (id, ideally) of the item is much more efficient than using $index for large datasets.

My example:
**ng-repeat-start="item in items track by item.id"**

https://docs.angularjs.org/api/ng/directive/ngRepeat
Best Practice: If you are working with objects that have a unique identifier property, you should track by this identifier instead of the object instance, e.g. item in items track by item.id. Should you reload your data later, ngRepeat will not have to rebuild the DOM elements for items it has already rendered, even if the JavaScript objects in the collection have been substituted for new ones. For large collections, this significantly improves rendering performance.
