### ISSUE TITLE
Pagination Problem

### ISSUE THREAD

**Issue by razzbee** [daniel-nagy/md-data-table#44]
Hello , I am having some problems with the pagination , it simply doesn't work, I checked the console and this was the error : Table Pagination: Could not locate your table directive, your onPaginationChange function will not work.

**Comment by daniel-nagy** [comment]
The pagination directive is located outside the table directive so when you register your trigger handler  the pagination directive attempts to locate the table directive. It does this as follows,

1. Starting from the pagination directive walk up the DOM tree until the `md-data-table-toolbar` element is found.

2. From the `md-data-table-toolbar` element walk the previous element siblings until the `md-data-table-container` element is found.

3. Select the first element child of the `md-data-table-container` element.

In other words, it expects that an `md-data-table-toolbar` is a ancestor of your pagination element and that `md-data-table-container` is a previous sibling of that `md-data-table-toolbar`.

The pagination directive really only needs to locate the table directive for the progress indicator to be displayed if your trigger handler returns a promise. If you need to have your template set up in such a way that these three steps will fail, I can change it so that your trigger handler will still work but a progress indicator will not be displayed. You could then always use the `md-progress` attribute to show the progress indicator.

**Comment by razzbee** [comment]
Thank You very much, it was a little typo in my code I .. Thank You, I have now fixed it
