### ISSUE TITLE
md-trigger with controllerAs syntax in ES2015

### ISSUE THREAD

**Issue by brad-decker** [daniel-nagy/md-data-table#46]
Greetings i'm using babel to build my controllers, and everything works correctly until it comes time to use the functions passed into md-trigger. 

The problem is that in my controller functions i'm using "this". here's a code snippet

    export default class MainController {
        query = {
            order: 'name',
            filter: '',
            page: 1,
            limit: 10,
            market: 'All Markets',
            region: 'All Regions'
        };

       constructor () {
            this.pageChanged( 1, 10 );
       }
       pageChanged( page, limit ) {
           return this.$Property.get( ..... ).$promise;
       }
    }

The above code is not complete, but it shows at least what i'm interested in figuring out. When the controller is called, it correctly loads the first page of ten properties, when attempting to use the pagination, however, i get an error message that this.$Property is undefined - and if i console.log( this ) it comes up undefined. 

Any advice?

**Comment by daniel-nagy** [comment]
@brad-decker I'm not too familiar with ECMAScript 6. I'm guessing in your template somewhere you have,

```html
<tag ng-controller="MainController as myCtrl"></tag>
```

and in your pagination element,

```html
<md-data-table-pagination md-trigger="myCrtl.pageChanged"></md-data-table-pagination>
```

I just tested the controllerAs syntax in the demo app and the value of `this` from inside the `pageChanged` function is the scope of the pagination directive. Inside the pagination directive I have,

```javascript
scope: {
  mdTrigger: '='
}
```

instead of,

```javascript
scope: {
  mdTrigger:  '&'
}
```

meaning the function is executed in the scope of the pagination directive, maybe I should change this?

I'm confused as to where `$Property` is coming from? My guess is it is a service being injected into your controller? In that case don't believe it would be available from `this` unless it was placed on the scope or assigned to `this` in your controller, i.e. `this.$Property = $Property`.

One thing you might want to try is to assign a variable to `this` from in your controller. For example, 

```javascript
var self = this;

pageChanged(page, limit) {
  return self.$Property.get( ..... ).$promise;
}
```

**Comment by brad-decker** [comment]
$Property is exposed on this. from the injection system i have created in order to access dependencies throughout the child functions. Basically the constructor is called with $Property as a parameter, and then i assign this.$Property = $Property so that the functions have access to it. 

I could create a global self variable and set it to the instance in the constructor as a potential workaround.

**Comment by daniel-nagy** [comment]
I would give that a shot. I just tried,

```javascript
scope: {
  mdTrigger: '&'
}
```

inside the pagination directive and it appears the value of `this` from inside the `pageChanged` function is the wrapper function Angular creates.

**Comment by audiodude** [comment]
Hello,

I'm not using ES2015, but I _am_ using `controller as` syntax with ngRoute.

I have the following:
```
          <thead md-order="projectList.order"
                 md-trigger="projectList.createSortValues">
```

However when createSortValues is called, `this` is a reference to a Scope of some sort instead of a reference to the `projectList` controller.

I am working withing strict style standards and therefore don't have the option of creating a global variable that references the controller. Any ideas?

**Comment by jadjoubran** [comment]
I have the same issue

**Comment by lorderb** [comment]
In ES6 use fat arrow to bind this:

```javascript
class IndexController {
    constructor() {
        this.onPaginationChange = (page, limit) => {
            console.log(this, page, limit); // this is the controller
            ...
        };
    }
}
```

```
<md-table-pagination md-limit="..." md-page="..." md-total="..." md-on-paginate="ctrl.onPaginationChange" ></md-table-pagination>
```
