### ISSUE TITLE
Is ES6 compatibility supported?

### ISSUE THREAD

**Issue by josoroma** [daniel-nagy/md-data-table#494]
Hi!

Using the https://github.com/AngularClass/NG6-starter we found some uses using `this` on the controller and `$ctrl` on the template, so we end up using a non pretty hack: `this.$scope`

```
       $scope.query.offset = $scope.query.page - 1;
       $scope.promise = $http.get('/api/things', {params: $scope.query})
         .then((response) => {
           $scope.totalCount = response.data.meta.paging.total_count;
           $scope.assessments = response.data.assessments;
         });
  ```

Thanks in advance!

**Comment by mcblum** [comment]
I think I have the same issue, @josoroma. When I call a function, such as from md-on-reorder, `this` is undefined in my controller. Using ES5 everything works great. Did you end up finding a good solution?

**Comment by josoroma** [comment]
No yet @mcblum

**Comment by fatore** [comment]
I've struggled with that as well...

In the end the less ugly of the hacks was to bind my method in the class constructor:

`
class ModelsTableController {
  constructor() {
    this.updateTable = this.updateTable.bind(this);
  }

  updateTable() {
    console.log('called updateTable');

    this.onUpdate();
  }
}
`

**Comment by josoroma** [comment]
I finally did it last Friday using arrow functions:

```
this.scope.get = ()  => { this.get(); };
```

```
  get() {
    ...
  };
```

Thanks!

**Comment by Vicente69** [comment]
Hi all,

I encountered exactly the same issue today, but reading this discussion, it seems a workaround 'only' has been identified, and the issue was closed, though it is not fixed or handled in this project.

To me, the issue shall be reopened until a clear answer is given: does md-data-table supports or will support ES6 in a next release?

Thanks in advance for your answer.
BR,
Vincent
