### ISSUE TITLE
pagination issue 

### ISSUE THREAD

**Issue by eniniz** [daniel-nagy/md-data-table#502]
I'm using the md.data.table to display data that I get from the backend.
there is a lot of data in the back (~40000 row) so I'm using backend pagination which is:
 in the fist time I get 100 row from the backend so with a limit of 10, the user can see, and use pagination of the first 10 pages, when the user ask for a page in [11,20] a new request is sent to get the newt 100 rows, and so on.
my problem is that when I get a new 100 row from  the back (for example the user select the 11th page) I get the result but **the page number return to 1** I tried to set it by: `paginationParams.page=11` but it doesn't work
can any one help.
thank you in advance :)

**Comment by eniniz** [comment]
I find the solution my self, and here is the solution for those who will have the same issue 
the problem was that when I send the request the get the next 100 rows, I copy it in the variable used to show the first 100 rows.
so the solution is, instead of copy the result in the variable, I add them to it, and that solve the problem

**Comment by 1mike12** [comment]
It was not clear to me either that the pagination examples given was only for clientside. What happened for me was that if I changed pagination, the data is loaded, but nothing is shown.

The key was to remove the clientside limits in the ng-repeat, so that  the controller is not splicingin data that is not there. 

`limitTo: $ctrl.limit : ($ctrl.page -1) * $ctrl.limit`
