### ISSUE TITLE
Display flex on toolbar disables angular material design flex

### ISSUE THREAD

**Issue by gaboAcosta** [daniel-nagy/md-data-table#67]
I just found that if you try to add angular material design flex elements, they stop working because of the display flex on the css:

```
md-data-table-toolbar {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-align-items: center;
      -ms-flex-align: center;
          align-items: center;
  padding: 0 24px;
  height: 64px;
  background-color: #fff;
  box-sizing: border-box;
}
```

If this is a material design library, shouldn't you delegate this flex functionallity to the angular material design library?

**Comment by daniel-nagy** [comment]
are you trying to use layout attributes on the `md-data-table-toolbar` element?

**Comment by gaboAcosta** [comment]
Yes, we had an specification where the client asked for the search bar to only be one third of the width on desktop devices and the full width on mobile devices.

In order to achieve this we had to do a layout with two flex, one flex-gt-sm="70" and another flex-gt-sm="30"

I was banging my head trying to figure out why would it not work, only to find out that this css was messing with Angular Material's design flex cappabilities.

I think, that if you depend on Angular Material design to display your tables, maybe you could just apply the flex directive instead of the css?

**Comment by daniel-nagy** [comment]
I believe in most cases it is desirable for the toolbar to be displayed flex with flex direction row and items aligned center. This is how the `.md-toolbar-tools` class works in Angular Material. You can always override the styles of the `md-data-table-toolbar` element. For example,

```html
<md-data-table-toolbar layout="column"></md-data-table-toolbar>
```

will change the flex direction to `column`. Of course you can always slap your own class on the element and override any styles as you desire.

I suspect that your problem has nothing to do with the styles on the `md-data-table-toolbar` element. If the parent element of your `md-data-table-toolbar` element is either

* Not displayed flex, or
* It's flex direction is column

then `flex-gt-sm="30"` is not going to work the way you expect. I presume an `md-card` element is the parent of your `md-data-table-toolbar` element, which has a flex direction column. So what you really want to do is move `flex-gt-sm="30"` to the first child of your `md-data-table-toolbar` element i.e.

```html
<md-data-table-toolbar>
  <div class="search" `flex-gt-sm="30"`></div>
</md-data-table-toolbar>
```

and because the `md-data-table-toolbar` element is displayed flex with a flex direction `row` this should work the way you expect.
