### ISSUE TITLE
Transclude + bindToController + This directive?

### ISSUE THREAD

**Issue by brianfeister** [daniel-nagy/md-data-table#72]
I have a project that makes use of a few "wrapper" directive that put various shell UI elements in place for all of the pages of my application.  These directives make use of `controllerAs: 'directiveCtrl'` + `bindToController: true` + `transclude: true`.  I've got a codepen here where I can't access the bound parent controllers from inside your directive.  Sorry, I know this is a complex use case, other data tables have also choked on it, but wanted to put it out there in case I'm just doing something wrong.  Assuming you're not trying to re-invent the wheel and the directive consists of many child directives and $scopes, it should be possible, though I'm not 100% sure where it's breaking.  The `Change Val:` button that appears in the table header and the `Sodium` column both attempt to access the scopes of these wrapping directives, but fail to do so:

http://codepen.io/brianfeister/pen/pJYrZq

**Comment by daniel-nagy** [comment]
The problem is you have `scope: true` on you inner and outer wrapper directives. This is going to create a new scope for each directive. From reading the [$compile API](https://docs.angularjs.org/api/ng/service/$compile) it sounds like this new scope should still prototypically inherit from its parent scope so I'm not sure why this is an issue. Here is your [plunker](http://codepen.io/anon/pen/zGbpWg?editors=101) with the new scope commented out. It may be that you are creating a new scope purposefully, in that case this is not a solution to your problem.

**Comment by daniel-nagy** [comment]
Is this still an issue for you?
