### ISSUE TITLE
md-row-select is resetting atfer the table's content update

### ISSUE THREAD

**Issue by henlz** [daniel-nagy/md-data-table#96]
I'm doing a server side pagination and when I load the next page, the previous selection is gone. An option to disable this selected itens cleaning would be nice.

**Comment by daniel-nagy** [comment]
I don't think this would be wise. This means the user has the potential to modify stale data which could result in a data integrity violation. Although I suppose that just because the items are currently visible doesn't necessarily guard against this either.

I guess this is up for debate, I need a place I can take a poll. Maybe I will just offer a way to do this but disable it by default.

Another issue will be when all items are selected, I would need to set some sort of flag for the developer so they can perform an action on items in the data set.

**Comment by daniel-nagy** [comment]
@henlz I'm going to close this issue, could please read and comment on issue #98?
